In [17]:
import numpy as np 

In [18]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a + b)
print(a - b)
print(a * b)
print(np.sqrt(a))
print(np.exp(b))

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[1.         1.41421356 1.73205081 2.        ]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


In [19]:
a1 = np.array([5, 10, 15])
b1 = np.array([2,4,6])
print(a1 +b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(np.power(a1,3))

[ 7 14 21]
[3 6 9]
[10 40 90]
[2.5 2.5 2.5]
[ 125 1000 3375]


In [20]:
#BROADCASTINNNN

c1 = np.array([1,2,3])

#add

print('arr + 10', c1 + 10)

arr + 10 [11 12 13]


In [21]:
print('arr X 5', c1 * 5)

arr X 5 [ 5 10 15]


In [22]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(matrix)
print('add array to matrix', matrix + c1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
add array to matrix [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [26]:
a3 = np.array([2, 4, 6, 8])
b3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
c3 = np.array([[10,20,30], [40,50,60]])
d3 = np.array([1,2,3])
e3 = np.array([10,10,10])

print('multiply by 0.5', a3 * .5)
print('add array to 3x3', b3 + d3)
print('add 10 to a 2x3', c3 + e3)

multiply by 0.5 [1. 2. 3. 4.]
add array to 3x3 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
add 10 to a 2x3 [[20 30 40]
 [50 60 70]]


In [29]:
import time

size = 1_000_000
list1 = list(range(size))
start = time.time
list2 = [x *2 for x in list1]
print('python list time:', time - start)

#numpy array 

arr = np.arange(size)
start = time.time()
arr2 = arr1 * 2
print('numpy array time', time.time() - start)


TypeError: 'list' object is not callable