In [45]:
import numpy as np

In [46]:
#creating an array called array lol 
numbers = [1,2,3,4]
numpy_array = np.array(numbers)

In [47]:
print(array)

[1 2 3 4]


In [48]:
doubled  = numpy_array * 2
print(doubled)

[2 4 6 8]


In [49]:
#zeros
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
#ones
ones = np.ones((3,))
print(ones)

[1. 1. 1.]


In [51]:
#range_array
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


In [52]:
four_ones = np.ones((4,4))
print(four_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [53]:
range_array2 = np.arange(0,10)
print(range_array2)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
linspace = np.linspace(0,1, num=5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


In [55]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
#print element at row 1, column 2
print(matrix[0,1])

2


In [77]:
#print the mini matrix 
print(matrix[2:,1:])

[[ 8  9]
 [11 12]]


In [61]:
a = np.arange(1,10)
print(a)
print(a[0:5])


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


In [78]:
#reshaping arrays 

na = np.arange(1,13)
print(na)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [79]:
reshaped =na.reshape(3,4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [82]:
#extract a submatrix of the top left 2 x 2
print(reshaped[:2,:2])

[[1 2]
 [5 6]]


In [84]:
#flatten the array back to its original format 
flat = reshaped.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [94]:
print(reshaped[:,1:3].flatten())

[ 2  3  6  7 10 11]


In [93]:
# flatter = reshaped[:,1:3].flatten()
# print(flatter)

[ 2  3  6  7 10 11]
